### ISSUE TITLE
LoadError on Big Sur

### ISSUE THREAD

**Issue by KwisatzJim** [PeterCrozier/AirPrint#1]
Hi
I tried running the script on my 2019 iMac running macOS Big Sur 11.1 and got the following error:

Traceback (most recent call last):
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ubygems (LoadError)

**Comment by KwisatzJim** [comment]
after doing some research I found that I needed to change the first line of airprintfix.rb to "#!/usr/bin/env ruby -rrubygems"

but now I get the following error:
Traceback (most recent call last):
	1: from ./airprintfix.rb:160:in `<main>'
./airprintfix.rb:19:in `browse': private method `new' called for DNSSD::Service:Class (NoMethodError)

**Comment by PeterCrozier** [comment]
Jim,

It looks like the dnssd gem has had its API changed to use factory functions and access to the old functions has been deprecated by making them private.  However there is only a man page for documentation, the samples have not been updated and I could not get browsing to work when I tried today. 

This is an old project from 2013 which has outlived its usefulness.  I have not used this myself in years as my current printer is networked and advertises airprint by default. I can't afford the time to figure out why browsing with dnssd does not work.

The ruby script is only there to automate the writing of a shell script that advertises your printers as supporting airprint.  There is enough information in the readme.md for you to write that by hand for your setup if you want to pursue this approach.

I will take this project off github in due course.

Sorry.

Peter

**Comment by KwisatzJim** [comment]
Ok I understand. Thanks for the reply!


Jim Kelley

**Comment by KwisatzJim** [comment]
Update:

I had posted on stackoverflow.com about the error and asked if anyone knew how to fix it and someone replied!
Here’s what they suggested and I tried it out and it’s working:

 def browse(s=self.service, d=self.domain, t=self.timeout)
    browser = DNSSD::Service.new  #REMOVE  this line
    printers=[]
    t = Thread.new do
        puts "Browsing for #{s} services in domain #{d}..."
        DNSSD.browse s, d do |reply| #EDIT this Line
          resolver = DNSSD::Service.new #REMOVE this line 
          DNSSD.resolve reply do |r| #EDIT this Line
            puts "Resolved #{r.name}"
            printers.push r
          end
        end
    end
    sleep self.timeout
    Thread.kill t
    # there might be more than one interface
    up = printers.uniq { |r| r.name }
    puts "Found #{up.count} unique from #{printers.count} entries" if up.count > 0
    up
  end

**Comment by igrayson** [comment]
I adapted that suggestion into a PR: https://github.com/PeterCrozier/AirPrint/pull/2
